#!/usr/bin/env bash
#
# Like ping(8), but for databases.
#
# usage:
#   pingDB postgresql db-host.rds.example.com
#   pingDB mysql db-host.rds.example.com

readonly sleep_time=1

readonly db_type="$1"

recommend_env_vars() {
  local vars=("$@")
  for var in "${vars[@]}"; do
    if [[ -z "$(printenv "$var")" ]] ; then
      echo You should set the "$var" env.var
    fi
  done
}


case "$db_type" in
  postgresql|postgres|pg)
    recommend_env_vars PGDATABASE PGHOST PGUSER PGPASSWORD PGPORT
    while sleep "$sleep_time"; do
      psql --no-password --quiet --tuples-only --command 'select CURRENT_TIMESTAMP'
    done
    ;;

  mysql)
    recommend_env_vars MYSQL_HOST MYSQL_TCP_PORT
    echo "sorry jim, I don't know how to do that"
    return 1
    ;;

  *)
    echo yo.  you did it wrong...
    return 2
    ;;
esac
