alias portal='bb -cp "$(clojure -Spath -Sdeps "{:deps {djblue/portal {:mvn/version \"0.11.2\"} clj-commons/clj-yaml {:mvn/version \"0.7.106\"}}}")" -m portal.main'
alias edn='portal edn'
alias json='portal json'
alias transit='portal transit'
alias yaml='portal yaml'
